# action.yml
name: 'Check for secrects'
description: 'Check for security vulnerabilities'
inputs:
  severity:  # id of input
    description: 'severity to catch'
    required: false
    default: "['CRITICAL']"
outputs:
  result: # id of output
    description: 'Scan results'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.severity }}